


vscode:
扩展：
    - webfreak.debug
    - danielpinto8zz6.c-cpp-project-generator
    - muhammad-sammy.csharp
    - redhat.java
- ms-dotnettools.vscode-dotnet-运行时
    - jbenden.c-cpp-flylint
    - franneck94.vscode-c-cpp-config
    - EdwinKofler.vscode-hyperupcall-pack-java
    - vadimcn.vscode-lldb
    - eamodio.gitlens
    - gattytto.go
    - ms-python.python
    - EricSia.pythonsnippets3
    - kyntrack.python-test
- franneck94.c-cpp-runner （英语）
- llvm-vs-代码扩展.vscode-clangd
    - franneck94.vscode-c-cpp-dev-extension-pack
